/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.CardLayout;
/**
 *
 * @author Lumin007 & tali-yuh
 */
public class PopupWindow extends javax.swing.JFrame
{
    private PopupWindow Pw;
    /**
     * Creates new form DetonatingCats
     */
    public PopupWindow()
    {
        initComponents();
        initializeEvents();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents()
    {

        DeathWindow = new DeathWindow();
        ErrorWindow = new ErrorWindow("");
        DefuseWindow = new DefuseWindow();
        MainGui = new MainGui();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(DeathWindow, "card1");
        getContentPane().add(ErrorWindow, "card2");
        getContentPane().add(DefuseWindow, "card3");

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
                {
                    new PopupWindow().setVisible(true);
            });
    }
    
    // Variables declaration - do not modify                     
    private DeathWindow DeathWindow;
    private DefuseWindow DefuseWindow;
    private ErrorWindow ErrorWindow;
    private MainGui MainGui;
    // End of variables declaration                   
    private int akt = 1;
    boolean io = false;
    
    /**
     * switcht zwischen den Pannels
     */
    public void switchPanel(int akt)
    {   
        ((CardLayout) getContentPane().getLayout()).show(getContentPane(), "card"+akt);
    }

    /**
     * initialisiert die Pannels
     */
    private void initializeEvents()
    {
        DeathWindow.setPw(this);
        ErrorWindow.setPw(this);
        DefuseWindow.setPw(this);
    }
    
    public void insertCard(int pPosition){
        MainGui.insertCard(pPosition);
    }
}